version: "3.9"
services:
    db:
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
            - 5252:5432
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
